// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyCSLxlKuX0TN_RTmWgZuZlvCe71lgWaLbY',
  //   appId: '1:716441948392:web:468fa49f50343bd5c5f95d',
  //   messagingSenderId: '716441948392',
  //   projectId: 'thrivers-8aa27',
  //   authDomain: 'thrivers-8aa27.firebaseapp.com',
  //   databaseURL: 'https://thrivers-8aa27-default-rtdb.europe-west1.firebasedatabase.app',
  //   storageBucket: 'thrivers-8aa27.appspot.com',
  //   measurementId: 'G-8KJ662BRWX',
  // ); // THRIVERS

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCvfKvmdjwSybcrHdiO2Hlcwk6AEm8Agj8",
      authDomain: "thriver-solutions.firebaseapp.com",
      projectId: "thriver-solutions",
      storageBucket: "thriver-solutions.appspot.com",
      messagingSenderId: "785314476138",
      databaseURL:"https://thriver-solutions-default-rtdb.firebaseio.com",
      appId: "1:785314476138:web:e3187b0595630c581ada13",
      measurementId: "G-38BJF6Z4C2"
  ); // THRIVERS SOLUTIONS

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW7ZLk_VRUC3ZmqB5IAa3_sQDXwGn4yss',
    appId: '1:716441948392:android:45550b9be4c5485dc5f95d',
    messagingSenderId: '716441948392',
    projectId: 'thrivers-8aa27',
    databaseURL: 'https://thrivers-8aa27-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'thrivers-8aa27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw8kPf9fsG7sz69Cfd_caPJkZ1kjbGn1Q',
    appId: '1:716441948392:ios:f66b1ce0025808d2c5f95d',
    messagingSenderId: '716441948392',
    projectId: 'thrivers-8aa27',
    databaseURL: 'https://thrivers-8aa27-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'thrivers-8aa27.appspot.com',
    iosBundleId: 'com.example.thrivers',
  );
}
